### ISSUE TITLE
整合 MCMOD 信息

### ISSUE THREAD

**Issue by z0z0r4** [MCLF-CN/docs#8]
### 检查项

- [X] 我充分理解提交的建议可能无法所有启动器作者参与，并尊重所有启动器开发者的选择
- [X] 我确认在Issues列表中并无其他人已经提出过与此问题相同或相似的问题
- [X] 我确认该反馈并非针对单个启动器的，如果是，我将会去该启动器的反馈页面反馈

### 您是什么类型的用户

第三方网站管理/负责人（MC相关的）

### 请简单的说一下您的想法

统一提供一份 MCMOD 相关的数据，包括译名等信息

### 它能解决什么样的问题/带来什么样的帮助

不清楚版权相关问题，只是各启动器多少都有自己的数据源，可以一并提供减少工作量

### 期望的结果

在 API 服务中提供，或者创建一个新 repo 定期维护

### 附注

不清楚站长是否会同意，没找到开放源

**Comment by ZhaiSoul** [comment]
这个要看mcmod的态度，比如BakaXL的信息是mcmod独家授权的，然后PCL好像是自己爬虫爬的…这玩意儿不太能我们做主张

**Comment by allMagicNB** [comment]
> 这个要看mcmod的态度，比如BakaXL的信息是mcmod独家授权的，然后PCL好像是自己爬虫爬的…这玩意儿不太能我们做主张

补充：PCL的译名信息在[这](https://github.com/Hex-Dragon/PCL2/blob/main/Plain%20Craft%20Launcher%202%2FResources%2FModData.txt)

**Comment by z0z0r4** [comment]
well，就我个人而言咋联系 mcmod 都不知道，因此在此提议，有没有 bigwig 对此有兴趣的，有想法去联系，虽然没有什么好处

当然要是不同意这 issue 就关了

**Comment by z0z0r4** [comment]
> > 这个要看mcmod的态度，比如BakaXL的信息是mcmod独家授权的，然后PCL好像是自己爬虫爬的…这玩意儿不太能我们做主张
> 
> 补充：PCL的译名信息在[这](https://github.com/Hex-Dragon/PCL2/blob/main/Plain%20Craft%20Launcher%202%2FResources%2FModData.txt?rgh-link-date=2024-02-04T01%3A54%3A13Z)

虽然我也知道这有一份，但显而易见容易过时、不方便公开使用，格式和内容问题等等，这就是为啥这有个提案了...

**Comment by ZhaiSoul** [comment]
因为这些数据牵扯到mcmod站方的核心数据，也是人家的立站之本，人家必然担心数据被其他竞品网站爬完的问题。

**Comment by allMagicNB** [comment]
但是我好像看到某条视频说龙猫和他们好像达成共识了，龙猫也没去爬了
但是我怀疑真实性

**Comment by z0z0r4** [comment]
总感觉，如果私下讨论的结果是否定的话，这个 issue 会很尴尬...

这个 issue 只是我看到 api.baka.zone 有 mcmod 相关接口起的念头，但既然这样我还是关闭吧，进雷区了捏

**Comment by zkitefly** [comment]
![Screenshot_2024-02-06-01-47-04-10_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/MCLF-CN/docs/assets/64117916/6e98a627-44f4-4061-ae3f-45123ed39dfb)
这个是当时和重生谈的，他**可能**到时候会出 api

**Comment by burningtnt** [comment]
那就把这个 Issue 再打开？

**Comment by zkitefly** [comment]
> 那就把这个 Issue 再打开？

数据又不是 MCLF 整合的（

**Comment by burningtnt** [comment]
继续追踪这个问题嘛……

**Comment by z0z0r4** [comment]
> > 那就把这个 Issue 再打开？
> 
> 数据又不是 MCLF 整合的（

姑且问问，是懒得整还是不希望公开？

懒得整的话他偶尔导出一份数据扔出来，看谁闲做个 api 也行 ~~姑且站界面挺老的看起来，有理由怀疑下（x~~

**Comment by zkitefly** [comment]
> > > 那就把这个 Issue 再打开？
> > 
> > 数据又不是 MCLF 整合的（
> 
> 姑且问问，是懒得整还是不希望公开？
> 
> 懒得整的话他偶尔导出一份数据扔出来，看谁闲做个 api 也行 ~~姑且站界面挺老的看起来，有理由怀疑下（x~~
> 
> 

应该问下重生才行
